# Generated by Django 3.2.16 on 2026-05-14 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_image'),
        ('blog', '0005_alter_post_author'),
    ]

    operations = [
    ]
